services:
  sensenova-u1-fast-demo:
    build: .
    ports:
      - "9012:8000"
    env_file:
      - path: .env
        required: false
    environment:
      SENSENOVA_BASE_URL: "https://token.sensenova.cn/v1"
      SENSENOVA_MODEL: "sensenova-u1-fast"
